python-clock solution
cmdellinger/exercism.io pull request #1
Opened 2016-11-02 18:20 UTC by cmdellinger

solution to exercism.io clock exercise in python

cc @barberj

2016-11-03 02:02 UTC, barberj commented on python/clock/clock.py
> +    def two_dig_str(self, x):
do you want your helper methods to be public?

2016-11-03 02:14 UTC, barberj commented on python/clock/clock.py
> +        self.time = self.clock_time(hours, minutes)
did you consider initializing and using a tuple for state? Would lend itself easier to manipulation in `add` and `subtract`

2016-11-03 02:17 UTC, barberj commented on python/clock/clock.py
> +        return self.time
the test shows passing the results of `add` and `subtract` to `str`. Would you expect the result of `add` to be a `str`?

2016-12-14 16:49 UTC, cmdellinger commented
I refactored the clock class.

cc @barberj

2016-12-16 12:49 UTC, barberj requested changes

2016-12-16 12:49 UTC, barberj commented on python/clock/clock.py
> +    def subtract(self, minutes): # -> String (XX:XX)
isn't subtract really just adding a negative number?

2016-12-16 12:49 UTC, barberj commented on python/clock/clock.py
> +        return self.__clock_str(self.time)
Why are you returning a str representation in add and subtract?

2016-12-16 20:05 UTC, cmdellinger commented
@barberj 
I updated based on your comments. The methods now return a Clock object and subtract just calls add.

2016-12-16 20:07 UTC, barberj approved these changes

2016-12-16 20:08 UTC, barberj commented
👍

2016-12-16 20:19 UTC, merged